wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1650885538
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 16
      4: 3.8.8
      5: 0.12.15
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.005
network:
  desc: null
  value: in->256->64
total_run:
  desc: null
  value: 2000
weight_decay:
  desc: null
  value: 0.05
